<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenDevelopAddin>true</OpenDevelopAddin>
    <OpenDevelopAddinKind>OutOfProcessHost</OpenDevelopAddinKind>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="GirCore.Gtk-4.0" Version="0.8.1" />
    <ProjectReference Include="..\..\..\Main\Designer\Designer.Remote\Designer.Remote.csproj" />
    <ProjectReference Include="..\..\..\Main\Designer\Designer.Server\Designer.Server.csproj" />
    <Compile Include="..\GtkDesigner\GtkUiDocumentEditor.cs" Link="GtkUiDocumentEditor.cs" />
  </ItemGroup>
  <Target Name="DeployToAddIns" AfterTargets="Build">
    <ItemGroup><HostOutput Include="$(TargetDir)**" /></ItemGroup>
    <Copy SourceFiles="@(HostOutput)" SkipUnchangedFiles="true"
      DestinationFiles="@(HostOutput->'$(MSBuildProjectDirectory)\..\..\..\..\AddIns\DisplayBindings\GtkDesigner\Host\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
