<Project Sdk="LibreWPF.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ICSharpCode.ClassDiagram</RootNamespace>
    <AssemblyName>ClassDiagramAddin</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <OutputPath>..\..\..\..\..\AddIns\DisplayBindings\ClassDiagram\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\ClassDiagram.Core.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" Private="False" />
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" Private="False" />
    <ProjectReference Include="..\..\..\..\Main\ICSharpCode.Core.Presentation\ICSharpCode.Core.Presentation.csproj" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\Main\GlobalAssemblyInfo.cs" Link="Configuration\GlobalAssemblyInfo.cs" />
    <Compile Include="Configuration\AssemblyInfo.cs" />
    <Compile Include="Src\ClassDiagramDisplayBinding.cs" />
    <Compile Include="Src\ClassDiagramViewContent.cs" />
    <Compile Include="Src\ShowClassDiagramCommand.cs" />
    <None Include="ClassDiagramAddin.addin" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
