#!/usr/bin/env pwsh
#
# dist.ps1 — build a framework-dependent OpenDevelop distribution for local testing.
# Mirrors the CI steps in .github/workflows/package.yml. Replaces the former dist.macos.ps1 and
# dist.windows.ps1, which were ~85% identical and drifted apart every time one side was touched.
#
# The whole publish/patch/AddIn-build pipeline is platform-neutral and lives here once. Only the
# final packaging stage differs, and it is isolated in Invoke-MacPackaging / Invoke-WindowsPackaging
# at the bottom:
#
#   macOS   -> OpenDevelop.app bundle, then OpenDevelop-macos.dmg
#   Windows -> one OpenDevelop-win-<rid>/ payload directory and OpenDevelop-windows-<rid>.zip PER
#              RuntimeIdentifier (see -RuntimeIdentifiers below)
#
# Note the app runs on LibreWPF (portable WPF) on Windows too — SharpDevelop.csproj strips the
# Microsoft.WindowsDesktop.App runtime framework on EVERY platform — which is why the LibreWinForms
# deps.json patch and the LibreWPF.Transport overlay below are not macOS-specific. The Win32
# compatibility shims (kernel32.dll, user32.dll, ...) the macOS bundle carries are emitted by
# LibreWPF.Sdk only on OSX/Linux and must NOT appear on Windows, where those names belong to the
# real OS DLLs; that split is handled by OpenDevelopDistributionRidFamily, not here.
#
# Windows: one package per architecture, not "Any CPU". ProGPU/LibreWPF ship real native
# libraries (glfw3.dll, wgpu_native.dll, vcruntime140_cor3.dll, DirectX/Vulkan interop shims, ...),
# and a native DLL is inherently architecture-specific - there is no "Any CPU" for P/Invoke'd code.
# Without an explicit -p:RuntimeIdentifier, the SDK implicitly resolves native assets for whatever
# architecture the machine RUNNING this script happens to be (dotnet --info's own RID), which is
# how a previous run on an ARM64 dev machine silently produced only a win-arm64 package. Passing
# -RuntimeIdentifiers explicitly (default: both) makes the output deterministic regardless of the
# build machine's own architecture, and produces a correct package for each target.
#
# Usage: ./dist.ps1 [-SkipPublish] [-Configuration Debug|Release]
#   -SkipPublish            reuse existing publish output (faster iteration on packaging)
#   -Configuration Debug    package the Debug configuration instead of Release.
#
# On macOS this is normally reached through ./dist.macos.sh, which only locates pwsh.
#

[CmdletBinding()]
param(
    [switch]$SkipPublish,
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $repoRoot 'build/common.psm1') -Force

$config = $Configuration
$tfm = 'net10.0-windows'
$sln = Join-Path $repoRoot 'OpenDevelop.Mvp.slnx'
$hostProject = Join-Path $repoRoot 'src/Main/SharpDevelop/SharpDevelop.csproj'
$dotnet = Find-DotNetHost
$patchScript = Join-Path $repoRoot 'build/patch-librewinforms-deps.ps1'

# The Addin SDK's OpenDevelopPruneAddinDeploymentAssets target drops runtimes/win*, linux* and
# unix* only for the 'osx' family; on Windows those win* assets are exactly what the payload needs.
$ridFamily = if ($IsWindows) { 'win' } else { 'osx' }

function New-TempDir {
    $p = Join-Path ([System.IO.Path]::GetTempPath()) ("opendevelop-" + [System.Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $p | Out-Null
    return $p
}


function Get-PinnedGitVersionProperties {
    <#
      src/Main/GlobalAssemblyInfo.cs is regenerated by Directory.Build.targets'
      OpenDevelopGenerateGlobalAssemblyInfo target, which invokes the GitVersion.MsBuild task
      independently IN EVERY PROJECT THAT LINKS THE FILE (~60 of them), including inside the
      later solution-wide "Build-Solution" AddIns pass below. GitVersion.MsBuild is not immune to
      producing a different CommitsSinceVersionSource between two separate top-level `dotnet`
      invocations a few seconds apart (observed: host published as revision 1, then the AddIns
      build silently rewrote the shared GlobalAssemblyInfo.cs to revision 2 partway through -
      WriteOnlyWhenDifferent still overwrites when the content DOES differ). Since the host DLL
      was already compiled and published against the OLD value, any AddIn compiled against the
      NEW value references a host assembly version that no longer exists on disk, throwing
      FileNotFoundException at runtime (e.g. GitAddIn's "ICSharpCode.SharpDevelop, Version=X"),
      which used to cascade into a hard crash showing the error dialog.
      Fix: read back the exact values the host publish step already committed to disk, and pass
      them as explicit -p:GitVersion_* MSBuild global properties to the AddIns build below.
      Global properties set via the command line cannot be overridden by a property assignment
      inside the build (GitVersion.MsBuild's own output is silently ignored once these are set),
      so every one of the ~60 projects is now guaranteed to compute byte-identical text and the
      shared file is never rewritten mid-pipeline.
    #>
    param([Parameter(Mandatory)][string]$GlobalAssemblyInfoPath)

    if (-not (Test-Path $GlobalAssemblyInfoPath)) {
        throw "dist.ps1: cannot pin GitVersion - $GlobalAssemblyInfoPath was not generated by the host publish"
    }
    $content = Get-Content -LiteralPath $GlobalAssemblyInfoPath -Raw
    $extract = { param($name)
        $m = [regex]::Match($content, "public const string $name = `"([^`"]*)`"")
        if (-not $m.Success) { throw "dist.ps1: cannot find RevisionClass.$name in $GlobalAssemblyInfoPath" }
        return $m.Groups[1].Value
    }
    $shaMatch = [regex]::Match($content, 'AssemblyInformationalVersion\(RevisionClass\.FullVersion \+ "\+([^"]*)"\)')
    if (-not $shaMatch.Success) { throw "dist.ps1: cannot find the informational-version sha suffix in $GlobalAssemblyInfoPath" }

    return @(
        "-p:GitVersion_Major=$(& $extract 'Major')",
        "-p:GitVersion_Minor=$(& $extract 'Minor')",
        "-p:GitVersion_Patch=$(& $extract 'Build')",
        "-p:GitVersion_CommitsSinceVersionSource=$(& $extract 'Revision')",
        "-p:GitVersion_FullSemVer=$(& $extract 'FullVersion')",
        "-p:GitVersion_ShortSha=$($shaMatch.Groups[1].Value)"
    )
}

function Build-MicrosoftDesignerHosts {
    <#
      Builds the genuine-Microsoft-framework designer backends that are NOT referenced by
      OpenDevelop.Mvp.slnx and therefore never get built by Build-Solution:
        - FormsDesigner\MicrosoftHost\Host (Windows Forms against the .NET Desktop Runtime)
        - WinUIXamlDesigner.MicrosoftHost  (real WinUI 3, multi-targets net9.0/net10.0)

      Each one is its own DeployToAddIns target (AfterTargets="Build") that copies straight into
      the shared AddIns/ tree, mirroring how the solution-referenced AddIns deploy themselves - so
      building these two projects on the side, before the AddIns copy step, is sufficient; nothing
      else needs to know they exist.

      WinUIXamlDesigner.MicrosoftHost specifically CANNOT be built by `dotnet build`: UseWinUI
      pulls in MrtCore.PriGen.targets, whose tasks ship only with Visual Studio (MSB4062
      otherwise) - see "Building WinUIXamlDesigner.MicrosoftHost" in CLAUDE.md. Both projects are
      therefore built with Visual Studio's MSBuild.exe.

      The Forms host is an ordinary managed child launched via "dotnet exec", so it builds RID-less.
      The WinUI host is a real unpackaged WinUI 3 app and cannot: one platform-neutral distribution
      must therefore carry a child per supported Windows architecture, each deployed under
      MicrosoftHost\<CLR major>\<rid>\ and selected by MicrosoftWinUIDesignRuntimeHostBootstrap.
    #>
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [ValidateSet('Debug', 'Release')]
        [string]$Configuration = 'Debug',
        [string[]]$PinnedGitVersionProperties = @()
    )

    $msbuild = Find-VsMsBuild
    Write-Host "==> Using Visual Studio MSBuild for Microsoft designer hosts: $msbuild"

    $formsDesignerHost = Join-Path $RepoRoot 'src/AddIns/DisplayBindings/FormsDesigner/MicrosoftHost/Host/MicrosoftFormsDesigner.Host.csproj'
    Write-Host '==> Building Microsoft Windows Forms design host (RID-less)...'
    Invoke-Native $msbuild $formsDesignerHost '-restore' "-p:Configuration=$Configuration" '-p:DisableGitVersionTask=true' '-p:ProGpuWpfUseCurrentRuntimeIdentifier=false' '-v:m' @PinnedGitVersionProperties

    $winUiHost = Join-Path $RepoRoot 'src/AddIns/DisplayBindings/WinUIXamlDesigner/WinUIXamlDesigner.MicrosoftHost/WinUIXamlDesigner.MicrosoftHost.csproj'
    foreach ($rid in 'win-x64', 'win-arm64') {
        Write-Host "==> Building Microsoft WinUI design host (RuntimeIdentifier=$rid)..."
        $winUiArgs = @('-restore', "-p:Configuration=$Configuration", '-p:DisableGitVersionTask=true', "-p:RuntimeIdentifier=$rid", '-v:m') + $PinnedGitVersionProperties
        Invoke-Native $msbuild $winUiHost @winUiArgs
    }
}

function Test-PackagedAppStartup {
    <#
      Launch the packaged app and require it to STAY up. A distribution that is missing or
      mismatching a runtime assembly does not fail the build — it throws at boot, which is exactly
      what the deps.json patch exists to prevent. Dump the captured output on an early exit so the
      cause is visible without re-running by hand.

      The payload is apphost-free, so callers pass the user's dotnet host and the app dll.
    #>
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [string[]]$ArgumentList = @(),
        [string]$WorkingDirectory
    )
    $tag = [System.Guid]::NewGuid().ToString('N')
    # Start-Process rejects using ONE file for both streams; keep two.
    $outLog = Join-Path ([System.IO.Path]::GetTempPath()) "opendevelop-smoke-$tag.out.log"
    $errLog = Join-Path ([System.IO.Path]::GetTempPath()) "opendevelop-smoke-$tag.err.log"

    $startArgs = @{
        FilePath               = $FilePath
        RedirectStandardOutput = $outLog
        RedirectStandardError  = $errLog
        PassThru               = $true
    }
    if ($ArgumentList.Count -gt 0) { $startArgs.ArgumentList = $ArgumentList }
    if ($WorkingDirectory) { $startArgs.WorkingDirectory = $WorkingDirectory }
    $proc = Start-Process @startArgs

    $ok = $true
    for ($i = 0; $i -lt 10; $i++) {
        Start-Sleep -Seconds 1
        if ($proc.HasExited) { $ok = $false; break }
    }
    if (-not $ok) {
        Write-Host "dist.ps1: packaged app exited during startup (status $($proc.ExitCode))" -ForegroundColor Red
        foreach ($log in $outLog, $errLog) {
            if (Test-Path $log) { Get-Content $log -TotalCount 160 | Write-Host }
        }
        Remove-Item -Force $outLog, $errLog -ErrorAction SilentlyContinue
        exit 1
    }

    # Ask the message loop to shut down before forcing the process, so the app releases its file
    # locks; on Windows a still-locked payload can otherwise be captured half-written by the .zip.
    try { $proc.CloseMainWindow() | Out-Null } catch {}
    Start-Sleep -Seconds 2
    if (-not $proc.HasExited) { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }
    Remove-Item -Force $outLog, $errLog -ErrorAction SilentlyContinue
    Write-Host 'Packaged app startup smoke test passed'
}


function Test-WindowsDistributionPayload {
    param([Parameter(Mandatory)][string]$PayloadRoot)

    $app = Join-Path $PayloadRoot 'OpenDevelop.dll'
    if (-not (Test-Path -LiteralPath $app)) { throw "Distribution payload has no OpenDevelop.dll: $PayloadRoot" }
    # AnyCPU and apphost-free: the app is started as "dotnet OpenDevelop.dll" with the user's own
    # .NET host. An apphost is the one file a build emits for a single architecture, so its presence
    # means the payload is no longer platform-neutral.
    if (Test-Path -LiteralPath (Join-Path $PayloadRoot 'OpenDevelop.exe')) {
        throw "Distribution payload contains an architecture-specific apphost (OpenDevelop.exe): $PayloadRoot"
    }
    # Every supported architecture's native WPF runtime must be present side by side; the host picks
    # the matching one from deps.json runtimeTargets at startup.
    foreach ($rid in 'win-x64', 'win-arm64') {
        $native = Join-Path $PayloadRoot "runtimes\$rid\native\PresentationNative_cor3.dll"
        if (-not (Test-Path -LiteralPath $native)) {
            throw "Distribution payload is missing the $rid WPF native runtime: $native"
        }
    }
    $addIns = Join-Path $PayloadRoot 'AddIns'
    if (-not (Test-Path -LiteralPath $addIns)) { throw "Distribution payload has no AddIns directory: $PayloadRoot" }
    if (@(Get-ChildItem -LiteralPath $addIns -Recurse -File -Filter '*.addin').Count -eq 0) { throw "Distribution payload has no addin manifests: $addIns" }

    # The WPF designer ships two mutually-exclusive out-of-process hosts - LibreWPF's own
    # portable runtime (Host\) and the genuine Microsoft WPF host that runs against the
    # machine's installed .NET Desktop Runtime (MicrosoftHost\). WpfSurfaceHostClient
    # deliberately refuses to fall back from one to the other at runtime (see
    # WpfSurfaceHostClient.StartAsync/AcquireSharedAsync), so a distribution missing either one
    # would leave that backend's projects unable to open a designer at all - fail the package
    # build now instead of shipping that silently.
    # Checked as .dll, not .exe: out-of-process hosts no longer generate an apphost (UseAppHost=false
    # in Directory.Build.targets) because DesignerHostProcessClient launches them as
    # "dotnet exec <host>.dll". The managed assembly is what actually has to be present.
    $wpfDesignRoot = Join-Path $addIns 'DisplayBindings\WpfDesign'
    foreach ($hostSpec in @(
        @{ SubDir = 'Host';          Exe = 'WpfDesign.SurfaceHost.dll';          Backend = 'LibreWPF' },
        @{ SubDir = 'MicrosoftHost'; Exe = 'MicrosoftWpfDesign.SurfaceHost.dll'; Backend = 'Microsoft WPF' }
    )) {
        $hostExe = Join-Path $wpfDesignRoot "$($hostSpec.SubDir)\$($hostSpec.Exe)"
        if (-not (Test-Path -LiteralPath $hostExe)) {
            throw "Distribution payload is missing the $($hostSpec.Backend) design host: $hostExe. " +
                "Both WPF designer backends must be built and deployed - check that every " +
                "src/AddIns/DisplayBindings/WpfDesign/MicrosoftHost/*.csproj project is referenced " +
                "by OpenDevelop.Mvp.slnx."
        }
    }

    # The Windows Forms and WinUI designers each have their own genuine-Microsoft-framework
    # backend, neither referenced by OpenDevelop.Mvp.slnx (WinForms.MicrosoftHost needs the
    # .NET Desktop Runtime; WinUIXamlDesigner.MicrosoftHost additionally needs UseWinUI's
    # MrtCore.PriGen.targets, which only ships with Visual Studio - see "Building
    # WinUIXamlDesigner.MicrosoftHost" in CLAUDE.md). Both are built by a dedicated
    # Build-MicrosoftDesignerHosts step, not the normal solution build, so verify their output
    # lands in the payload the same way the WPF check above does - a silent gap here is exactly
    # how this backend went unbuilt/unshipped before.
    $formsDesignerHostExe = Join-Path $addIns 'DisplayBindings\FormsDesigner\MicrosoftHost\MicrosoftFormsDesigner.Host.dll'
    if (-not (Test-Path -LiteralPath $formsDesignerHostExe)) {
        throw "Distribution payload is missing the Microsoft Windows Forms design host: $formsDesignerHostExe. " +
            "Check that Build-MicrosoftDesignerHosts built " +
            "src/AddIns/DisplayBindings/FormsDesigner/MicrosoftHost/Host/MicrosoftFormsDesigner.Host.csproj."
    }
    # The real WinUI 3 child is architecture-specific, so the single payload must carry one per
    # supported Windows RID under MicrosoftHost\<CLR major>\<rid>\. The bootstrap picks by CLR major
    # (from the designed app's runtimeconfig) and then by process architecture.
    $winUiHostRoot = Join-Path $addIns 'DisplayBindings\WinUIXamlDesigner\MicrosoftHost'
    foreach ($tfmDir in 'net9.0', 'net10.0') {
        foreach ($rid in 'win-x64', 'win-arm64') {
            $winUiHostExe = Join-Path $winUiHostRoot "$tfmDir\$rid\WinUIXamlDesigner.MicrosoftHost.dll"
            if (-not (Test-Path -LiteralPath $winUiHostExe)) {
                throw "Distribution payload is missing the Microsoft WinUI design host ($tfmDir/$rid): $winUiHostExe. " +
                    "Check that Build-MicrosoftDesignerHosts built " +
                    "src/AddIns/DisplayBindings/WinUIXamlDesigner/WinUIXamlDesigner.MicrosoftHost/WinUIXamlDesigner.MicrosoftHost.csproj " +
                    "with Visual Studio's own MSBuild.exe (dotnet build cannot build UseWinUI projects) for both win-x64 and win-arm64."
            }
        }
    }

    # PDBs, reference assemblies and foreign native assets are build-time artifacts. Their
    # presence means either an SDK target or the staging copy regressed, and makes the final ZIP
    # needlessly architecture/OS-agnostic rather than deployable.
    $forbidden = Get-ChildItem -LiteralPath $PayloadRoot -Recurse -File | Where-Object {
        $relative = $_.FullName.Substring($PayloadRoot.Length).Replace('\', '/').ToLowerInvariant()
        $_.Extension -in '.pdb', '.dylib', '.so' -or
        $relative -match '/ref/' -or
        $relative -match '/runtimes/(linux|unix|osx)'
    }
    if ($forbidden) {
        $sample = ($forbidden | Select-Object -First 12 -ExpandProperty FullName) -join [Environment]::NewLine
        throw "Distribution payload contains build-only or foreign assets:$([Environment]::NewLine)$sample"
    }
}

function Test-WindowsDistributionZip {
    param([Parameter(Mandatory)][string]$ZipPath)

    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead($ZipPath)
    try {
        $prefix = "OpenDevelop-win/"
        if (-not ($archive.Entries.FullName -contains "${prefix}OpenDevelop.dll")) { throw "ZIP lacks ${prefix}OpenDevelop.dll: $ZipPath" }
        if ($archive.Entries.FullName -contains "${prefix}OpenDevelop.exe") { throw "ZIP contains an architecture-specific apphost: $ZipPath" }
        if (-not ($archive.Entries.FullName | Where-Object { $_ -like "${prefix}AddIns/*.addin" })) { throw "ZIP lacks addin manifests: $ZipPath" }
        # Mirror the designer-host checks in Test-WindowsDistributionPayload - they must survive the
        # staging/zip round-trip, not just be present in the staged payload dir.
        $expected = @(
            "${prefix}AddIns/DisplayBindings/WpfDesign/Host/WpfDesign.SurfaceHost.dll",
            "${prefix}AddIns/DisplayBindings/WpfDesign/MicrosoftHost/MicrosoftWpfDesign.SurfaceHost.dll",
            "${prefix}AddIns/DisplayBindings/FormsDesigner/MicrosoftHost/MicrosoftFormsDesigner.Host.dll"
        )
        foreach ($tfmDir in 'net9.0', 'net10.0') {
            foreach ($rid in 'win-x64', 'win-arm64') {
                $expected += "${prefix}AddIns/DisplayBindings/WinUIXamlDesigner/MicrosoftHost/$tfmDir/$rid/WinUIXamlDesigner.MicrosoftHost.dll"
            }
        }
        foreach ($path in $expected) {
            if (-not ($archive.Entries.FullName -contains $path)) {
                throw "ZIP is missing a designer host: $path ($ZipPath)"
            }
        }
        $forbidden = $archive.Entries.FullName | Where-Object {
            $name = $_.ToLowerInvariant()
            $name.EndsWith('.pdb') -or $name.EndsWith('.dylib') -or $name.EndsWith('.so') -or
            $name -match '/ref/' -or $name -match '/runtimes/(linux|unix|osx)'
        }
        if ($forbidden) { throw "ZIP contains build-only or foreign assets:$([Environment]::NewLine)$(($forbidden | Select-Object -First 12) -join [Environment]::NewLine)" }
    } finally { $archive.Dispose() }
}

# ---------------------------------------------------------------------------------------------
# Shared pipeline (one AnyCPU pass - see Invoke-DistributionPipeline below)
# ---------------------------------------------------------------------------------------------
#
# Restore runs up front inside Invoke-DistributionPipeline with
# -p:ProGpuWpfUseCurrentRuntimeIdentifier=false, so every project's obj/project.assets.json has a
# RID-less target. On Windows this also seeds LibreWPF.Sdk resolution for the AvalonEdit submodule,
# whose own global.json has no "msbuild-sdks" entry and shadows the repo-root one for every project
# beneath it (otherwise MSB4236 "The SDK 'LibreWPF.Sdk' specified could not be found").

# ---------------------------------------------------------------------------------------------
# Platform packaging
# ---------------------------------------------------------------------------------------------

function Invoke-MacPackaging {
    Write-Host "==> Building framework-dependent .app bundle ($config)..."
    $env:DIST_CONFIG = $config
    & bash (Join-Path $repoRoot 'build/macos/build-application-bundle.sh')
    if ($LASTEXITCODE -ne 0) { throw "build-application-bundle.sh exited with code $LASTEXITCODE" }

    Write-Host '==> Smoke-testing packaged app...'
    Test-PackagedAppStartup -FilePath $dotnet -ArgumentList @((Join-Path $repoRoot 'OpenDevelop.app/Contents/MacOS/OpenDevelop.dll'))

    Write-Host '==> Building .dmg...'
    Push-Location $repoRoot
    try {
        & bash (Join-Path $repoRoot 'build/macos/build-dmg.sh') OpenDevelop.app OpenDevelop-macos.dmg
        if ($LASTEXITCODE -ne 0) { throw "build-dmg.sh exited with code $LASTEXITCODE" }
    }
    finally {
        Pop-Location
    }

    return (Join-Path $repoRoot 'OpenDevelop-macos.dmg')
}

function Invoke-WindowsPackaging {
    param([Parameter(Mandatory)][string]$PublishDir)

    # ONE platform-neutral payload/zip: the app is AnyCPU and apphost-free, and every
    # architecture's native/runtime assets live under runtimes/<rid>/ in the same tree.
    $payloadRoot = Join-Path $repoRoot 'OpenDevelop-win'
    $zipPath = Join-Path $repoRoot 'OpenDevelop-win.zip'

    Write-Host "==> Assembling the platform-neutral distribution payload ($config)..."
    if (Test-Path $payloadRoot) { Remove-Item -Recurse -Force $payloadRoot }
    New-Item -ItemType Directory -Path $payloadRoot | Out-Null
    Copy-Item -Path (Join-Path $PublishDir '*') -Destination $payloadRoot -Recurse -Force

    # `dotnet publish` may preserve symbol/reference files from a Debug (and occasionally a
    # cached Release) build. They are neither loaded by the framework-dependent app nor useful
    # to an end user, but previously dominated the Windows archive. Do this in staging so the
    # verified publish directory remains available for diagnostics and incremental builds.
    $hostBuildOnlyFiles = Get-ChildItem -LiteralPath $payloadRoot -Recurse -File | Where-Object {
        $relative = $_.FullName.Substring($payloadRoot.Length).Replace('\', '/').ToLowerInvariant()
        $_.Extension -eq '.pdb' -or $relative -match '/ref/' -or
        ($_.Extension -eq '.xml' -and (Test-Path -LiteralPath (Join-Path $_.DirectoryName "$($_.BaseName).dll")))
    }
    Remove-Item -LiteralPath $hostBuildOnlyFiles.FullName -Force -ErrorAction SilentlyContinue
    $hostReferenceDirs = Get-ChildItem -LiteralPath $payloadRoot -Recurse -Directory -Filter ref -ErrorAction SilentlyContinue
    foreach ($referenceDir in $hostReferenceDirs) { Remove-Item -LiteralPath $referenceDir.FullName -Recurse -Force }
    # A build still emits an apphost for the build machine's architecture; drop it so the payload
    # stays architecture-neutral (the app is started as "dotnet OpenDevelop.dll").
    Remove-Item -LiteralPath (Join-Path $payloadRoot 'OpenDevelop.exe') -Force -ErrorAction SilentlyContinue

    # A RID-less publish carries EVERY platform's native tree (linux/osx/unix) as well as Windows.
    # The other platforms are dead weight in the Windows package, so drop everything except the
    # Windows RIDs (win, win-x64, win-x86, win-arm64) before validating/zipping.
    foreach ($runtimesDir in Get-ChildItem -LiteralPath $payloadRoot -Recurse -Directory -Filter 'runtimes' -ErrorAction SilentlyContinue) {
        foreach ($ridDir in Get-ChildItem -LiteralPath $runtimesDir.FullName -Directory -ErrorAction SilentlyContinue) {
            if ($ridDir.Name -eq 'win' -or $ridDir.Name -like 'win-*') { continue }
            Remove-Item -LiteralPath $ridDir.FullName -Recurse -Force
        }
    }

    # OpenDevelop locates its addins and data at runtime by walking UP from the executable looking
    # for data/resources/languages/LanguageDefinition.xml (SharpDevelopMain.FindApplicationRootPath),
    # then loading *.addin from <root>/AddIns. The payload must therefore contain data/ and AddIns/
    # next to the executable so the walk resolves on the first step.
    Copy-Item -Path (Join-Path $repoRoot 'data') -Destination (Join-Path $payloadRoot 'data') -Recurse -Force

    # AddIn build outputs carry their full dependency closures. Anything already supplied by the
    # published host resolves from the application base directory, so skip those files by name
    # instead of copying ~2 GB and pruning afterwards. This also keeps stale XML docs, satellite
    # resources and native helpers from an old developer build out of the payload.
    $hostFiles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    Get-ChildItem -LiteralPath $payloadRoot -Recurse -File | ForEach-Object { [void]$hostFiles.Add($_.Name) }

    $addInsSource = (Resolve-Path (Join-Path $repoRoot 'AddIns')).Path
    $addInsTarget = Join-Path $payloadRoot 'AddIns'

    # OpenDevelopAddinKind=OutOfProcessHost projects (WinForms/WPF/WinUI design-surface hosts) run
    # as their own separate "dotnet exec" child process with its own working directory - unlike an
    # InProcess addin, they cannot resolve a same-named dependency from files sitting beside the
    # app dll, so the by-name dedup below must not strip files out of their deployment folders.
    # Missing this once (FormsDesigner's Host\ folder losing PresentationFramework.dll, every
    # ProGPU.*.dll, System.Windows.Forms.dll, ...) made the WinForms designer's child host crash
    # before completing its handshake, surfacing only as an opaque
    # "System.TimeoutException: The operation has timed out" with no further detail. Keep this in
    # sync with each OutOfProcessHost project's own DeployToAddIns destination.
    $outOfProcessHostDirs = @(
        'DisplayBindings\FormsDesigner\Host',
        'DisplayBindings\FormsDesigner\MicrosoftHost',
        'DisplayBindings\GtkDesigner\Host',
        'DisplayBindings\MewUIDesigner\Host',
        'DisplayBindings\WinUIXamlDesigner\UnoHost',
        'DisplayBindings\WinUIXamlDesigner\MicrosoftHost',
        'DisplayBindings\WpfDesign\Host',
        'DisplayBindings\WpfDesign\MicrosoftHost'
    )

    # Select first, then copy in a plain foreach. A ForEach-Object block runs in a child scope, so
    # a counter incremented inside one needs an explicit $script: qualifier — which silently
    # counted nothing once this loop moved inside a function. Keeping the copy in a normal loop
    # means the count and the filtering read the same way and cannot drift apart again.
    $addInFiles = Get-ChildItem -LiteralPath $addInsSource -Recurse -File | Where-Object {
        $name = $_.Name
        $relative = $_.FullName.Substring($addInsSource.Length).TrimStart('\', '/')
        $relativeDir = Split-Path -Parent $relative
        $isOutOfProcessHost = $outOfProcessHostDirs | Where-Object { $relativeDir -eq $_ -or $relativeDir.StartsWith("$_\") }
        -not ($name -like '*.pdb') -and
        -not ($name -like '*.dylib') -and
        -not ($name -like '*.so') -and
        -not ($name -like 'LeXtudio.DevFlow.*') -and
        -not ($name -like 'CliclickSharp*') -and
        -not ($relative -match '(^|[\\/])(ref|runtimes[\\/](linux|unix|osx))([\\/]|$)') -and
        -not ($_.Extension -eq '.xml' -and (Test-Path -LiteralPath (Join-Path $_.DirectoryName "$($_.BaseName).dll"))) -and
        (-not $hostFiles.Contains($name) -or $isOutOfProcessHost)
    }

    foreach ($file in $addInFiles) {
        $relative = $file.FullName.Substring($addInsSource.Length).TrimStart('\', '/')
        $destination = Join-Path $addInsTarget $relative
        $destinationDir = Split-Path -Parent $destination
        if (-not (Test-Path -LiteralPath $destinationDir)) {
            New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
        }
        Copy-Item -LiteralPath $file.FullName -Destination $destination -Force
    }
    Write-Host "    AddIn files copied: $(@($addInFiles).Count)"

    $appPath = Join-Path $payloadRoot 'OpenDevelop.dll'
    if (-not (Test-Path $appPath)) { throw "dist.ps1: packaged app not found: $appPath" }
    Test-WindowsDistributionPayload -PayloadRoot $payloadRoot
    Write-Host "Payload ready: $payloadRoot"

    Write-Host '==> Smoke-testing packaged app...'
    Test-PackagedAppStartup -FilePath $dotnet -ArgumentList @($appPath) -WorkingDirectory $payloadRoot

    Write-Host '==> Building .zip...'
    Remove-Item -LiteralPath $zipPath -Force -ErrorAction SilentlyContinue
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $payloadRoot, $zipPath,
        [System.IO.Compression.CompressionLevel]::Optimal,
        $true)
    Test-WindowsDistributionZip -ZipPath $zipPath

    return $zipPath
}

function Invoke-DistributionPipeline {
    # One AnyCPU pass: no -p:RuntimeIdentifier anywhere, so the output is a single RID-less
    # (platform-neutral) payload that carries every architecture's assets under runtimes/.
    $publishDir = Join-Path $repoRoot "src/Main/SharpDevelop/bin/$config/$tfm/publish"
    $depsJson = Join-Path $publishDir 'OpenDevelop.deps.json'

    Write-Host '==> Restoring solution...'
    Restore-Solution -DotNet $dotnet -Solution $sln -ExtraProperties @('-p:ProGpuWpfUseCurrentRuntimeIdentifier=false')

    if (-not $SkipPublish) {
        # Clear the shared intermediate output so publish cannot reuse artifacts left by a
        # previous build (of this RID, or of a differently-RID'd pass before this one). This
        # distribution intentionally remains framework-dependent and uses the installed .NET
        # runtime; the SDK-generated apphost is only the native entry point and does not bundle
        # that runtime.
        Write-Host '==> Cleaning intermediate outputs...'
        $hostObj = Join-Path $repoRoot "src/Main/SharpDevelop/obj/$config/$tfm"
        if (Test-Path $hostObj) { Remove-Item -Recurse -Force $hostObj }

        # Ensure clean state for ICSharpCode.Core.Presentation — its .g.resources (WPF theme
        # resource blob) can otherwise stale-cross from a previous build and produce a 12-byte
        # corrupt file that crashes at boot with EndOfStreamException in
        # FindResource/LoadThemedDictionary. Clear obj/ and bin/ entirely (not just the $config
        # subfolder) since an explicit -p:RuntimeIdentifier can binplace this project's output
        # under an additional RID-suffixed subfolder that the plain "$sub/$config" path misses.
        $corePres = Join-Path $repoRoot 'src/Main/ICSharpCode.Core.Presentation'
        foreach ($sub in 'obj', 'bin') {
            $dir = Join-Path $corePres $sub
            if (Test-Path $dir) { Remove-Item -Recurse -Force $dir }
        }

        Write-Host "==> Publishing framework-dependent AnyCPU app ($config)..."
        if (Test-Path $publishDir) { Remove-Item -Recurse -Force $publishDir }
        Invoke-Native $dotnet publish $hostProject -c $config --self-contained false `
            "-p:OpenDevelopDistributionBuild=true" `
            "-p:PublishDir=$publishDir" `
            "-p:ProGpuWpfUseCurrentRuntimeIdentifier=false"

        if (-not (Test-Path $publishDir)) {
            throw "dist.ps1: host publish directory not found: $publishDir"
        }

        # NuGet conflict resolution omits LibreWinForms from the standard publish closure.
        # Patch the final manifest and copy its matching runtime files.
        $nugetPackagesLine = & $dotnet nuget locals global-packages --list | Select-String '^global-packages: '
        if (-not $nugetPackagesLine) {
            throw 'dist.ps1: cannot determine the NuGet global-packages directory'
        }
        $nugetPackages = ($nugetPackagesLine.Line -replace '^global-packages:\s*', '')
        & $patchScript $depsJson $nugetPackages

        # Some projects write to OpenDevelopHostPublishDir while computing their distribution
        # closure. Give that build a disposable copy so the verified host deployment above
        # remains immutable.
        $hostPublishSnapshot = New-TempDir
        Copy-Item -Path (Join-Path $publishDir '*') -Destination $hostPublishSnapshot -Recurse -Force

        # AddIns/ is an ignored deployment directory, not source. A partial or cross-platform
        # build used to leave .so/.dylib, ref/, package build props and stale assemblies here;
        # later package runs then copied them even though the current solution never produced
        # them. Start every distribution build with a genuinely empty deployment root.
        Write-Host '==> Cleaning generated AddIn deployment root...'
        $generatedAddIns = Join-Path $repoRoot 'AddIns'
        if (Test-Path $generatedAddIns) { Remove-Item -LiteralPath $generatedAddIns -Recurse -Force }
        New-Item -ItemType Directory -Path $generatedAddIns | Out-Null

        # Pin every AddIn to the EXACT GitVersion values the just-published host assembly was
        # compiled against - see Get-PinnedGitVersionProperties for why this is required.
        $globalAssemblyInfo = Join-Path $repoRoot 'src/Main/GlobalAssemblyInfo.cs'
        $pinnedGitVersionProperties = Get-PinnedGitVersionProperties -GlobalAssemblyInfoPath $globalAssemblyInfo

        Write-Host '==> Building distribution AddIns without shared runtime copies...'
        Build-Solution -DotNet $dotnet -Solution $sln -Configuration $config -ExtraProperties (@(
            '-p:OpenDevelopDistributionBuild=true',
            "-p:OpenDevelopDistributionRidFamily=$ridFamily",
            "-p:OpenDevelopHostPublishDir=$hostPublishSnapshot",
            '-p:ProGpuWpfCopyPackageRuntimeAssets=false',
            '-p:ProGpuWpfUseCurrentRuntimeIdentifier=false'
        ) + $pinnedGitVersionProperties)

        if ($IsWindows) {
            Write-Host '==> Building Microsoft-framework designer hosts (VS MSBuild)...'
            Build-MicrosoftDesignerHosts -RepoRoot $repoRoot -Configuration $config `
                -PinnedGitVersionProperties $pinnedGitVersionProperties
        }
        Remove-Item -Recurse -Force $hostPublishSnapshot

        # The solution traversal may copy reference assemblies over the original PublishDir
        # through cached project state. Restore the authoritative package runtime payload only
        # after every build has completed.
        & $patchScript $depsJson $nugetPackages
    }
    else {
        Write-Host '==> Skipping publish (-SkipPublish)'
    }

    if (-not (Test-Path $publishDir)) {
        throw "dist.ps1: framework-dependent publish directory not found: $publishDir"
    }

    if ($IsWindows) { Invoke-WindowsPackaging -PublishDir $publishDir }
    else { Invoke-MacPackaging }
}

$artifact = Invoke-DistributionPipeline

Write-Host ''
Write-Host "Done: $artifact"
