using System.Text;

namespace LeXtudio.MewUI.Xaml;

/// <summary>
/// Emits the strict, WinForms-style InitializeComponent partial class from an .mxaml document
/// (see doc/technotes/mxaml.md and the grammar section of mewui-designer.md). Ordered sections:
/// field declarations → constructions → property/event assignments per node → relationship
/// calls per container → Content = root. No `this.` prefix, no initializers.
/// </summary>
public static class MewUICSharpGenerator
{
	public static string Generate(MxamlDocument document)
	{
		var ns = document.Class[..document.Class.LastIndexOf('.')];
		var className = document.Class[(ns.Length + 1)..];
		var root = document.Root;

		var controls = root.DescendantsAndSelf().Where(o => o.Type != "Window").ToList();

		var sb = new StringBuilder();
		sb.Append("// <auto-generated>Generated from ").Append(root.Name).Append(".mxaml - DO NOT EDIT.").Append('\n');
		sb.Append("// Changes will be overwritten the next time the designer or build runs.</auto-generated>\n");
		sb.Append("using Aprillz.MewUI;\nusing Aprillz.MewUI.Controls;\n\nnamespace ").Append(ns).Append(";\n\n");
		sb.Append("public partial class ").Append(className).Append('\n');
		sb.Append("{\n");

		foreach (var c in controls)
			sb.Append("    private ").Append(c.Type).Append(' ').Append(c.Name).Append(" = null!;\n");

		sb.Append("\n    private void InitializeComponent()\n    {\n");

		foreach (var c in controls)
			sb.Append("        ").Append(c.Name).Append(" = new ").Append(c.Type).Append("();\n");

		sb.Append('\n');

		// Window-level properties first (Title/Width/...), then each control's block.
		foreach (var a in root.Attributes)
		// Root Window-level props: instance members, NO owner prefix.
		foreach (var attr in root.Attributes) {
			var kind = MewUIControlCatalog.KindOf("Window", attr.Name);
			switch (kind) {
				case MxamlPropertyKind.String:
					sb.Append("        ").Append(attr.Name).Append(" = \"").Append(Escape(attr.Value)).Append("\";\n");
					break;
				case MxamlPropertyKind.Double:
					sb.Append("        ").Append(attr.Name).Append(" = ").Append(DoubleLiteral(a.Value)).Append(";\n");
					break;
				default:
					sb.Append("        // unsupported: ").Append(attr.Name).Append("\n");
					break;
			}
		}

		foreach (var c in controls) {
			sb.Append('\n');
			foreach (var a in c.Attributes)
				EmitAttribute(sb, c.Type, c.Name, a);
		}

		sb.Append('\n');

		// Relationship calls: each container expresses how it holds its children.
		// Only actual Panel subclasses use .Children(); ContentControl types use .Content;
		// Border uses .Child. The root Window's Content is set to its first container child.
		foreach (var container in containersInDependencyOrder(root)) {
			if (container.Type == "Window") continue; // root Content assignment below
			if (container.Children.Count == 0) continue;
			var mode = MewUIControlCatalog.ContainmentMode(container.Type);
			switch (mode) {
				case "Children":
					sb.Append("        ").Append(container.Name).Append(".Children(")
					   .Append(string.Join(", ", container.Children.Select(ch => ch.Name)))
					   .Append(");\n");
					break;
				case "Content":
					if (container.Children.Count == 1)
						sb.Append("        ").Append(container.Name).Append(".Content = ")
						   .Append(container.Children[0].Name).Append(";\n");
					break;
				case "Child":
					if (container.Children.Count >= 1)
						sb.Append("        ").Append(container.Name).Append(".Child = ")
						   .Append(container.Children[0].Name).Append(";\n");
					break;
			}
		}

		var contentRoot = root.Children.FirstOrDefault()?.Name ?? "";
		sb.Append("        Content = ").Append(contentRoot).Append(";\n");
		sb.Append("    }\n}");
		return sb.ToString();
	}

	static void EmitAttribute(StringBuilder sb, string ownerType, string ownerName, MxamlAttribute attribute)
	{
		if (attribute.IsEvent) {
			sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
			  .Append(" += ").Append(attribute.Value).Append(";\n");
			return;
		}
		switch (MewUIControlCatalog.KindOf(ownerType, attribute.Name)) {
			case MxamlPropertyKind.String:
				sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
				  .Append(" = \"").Append(Escape(attribute.Value)).Append("\";\n");
				break;
			case MxamlPropertyKind.Double:
				sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
				  .Append(" = ").Append(DoubleLiteral(attribute.Value)).Append(";\n");
				break;
			case MxamlPropertyKind.Int32:
				sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
				  .Append(" = ").Append(int.Parse(attribute.Value, System.Globalization.CultureInfo.InvariantCulture)).Append(";\n");
				break;
			case MxamlPropertyKind.Boolean:
				sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
				  .Append(" = ").Append(attribute.Value.ToLowerInvariant()).Append(";\n");
				break;
			case MxamlPropertyKind.Enum:
				sb.Append("        ").Append(ownerName).Append('.').Append(attribute.Name)
				  .Append(" = ").Append(attribute.Name).Append('.').Append(attribute.Value).Append(";\n");
				break;
			default:
				// Unregistered property: emit a comment instead of possibly-wrong code so the
				// generated file keeps compiling while surfacing the gap (M-2 lesson).
				sb.Append("        // unsupported: ").Append(ownerName).Append('.')
				  .Append(attribute.Name).Append(" = \"").Append(Escape(attribute.Value)).Append("\"\n");
				break;
		}
	}

	static string DoubleLiteral(string value)
	{
		var invariant = double.Parse(value, System.Globalization.CultureInfo.InvariantCulture)
		    .ToString("R", System.Globalization.CultureInfo.InvariantCulture);
		return invariant.Contains('.') || invariant.Contains('E') || invariant.Contains('e') ? invariant : invariant + ".0";
	}

	static string Escape(string value) => value
		.Replace("\\", "\\\\")
		.Replace("\"", "\\\"")
		.Replace("\n", "\\n")
		.Replace("\r", "\\r")
		.Replace("\t", "\\t");

	// Containers ordered so parents precede children (DFS pre-order over the mxaml tree).
	static IEnumerable<MxamlObject> containersInDependencyOrder(MxamlObject root)
		=> root.DescendantsAndSelf().Where(o => o.Children.Count > 0);
}
