<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ICSharpCode.Designer.Remote</AssemblyName>
    <RootNamespace>ICSharpCode.SharpDevelop.Designer.Remote</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>
</Project>
