<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FormsDesigner.Remote</AssemblyName>
    <RootNamespace>ICSharpCode.FormsDesigner.OutOfProcess</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Project\Src\OutOfProcess\FormsDesignerHostClient.cs" Link="FormsDesignerHostClient.cs" />
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
    <ProjectReference Include="..\..\..\..\Main\Designer\Designer.Remote\Designer.Remote.csproj" />
    <ProjectReference Include="..\Host\FormsDesigner.Host.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
