// Copyright (c) 2010-2013 AlphaSierraPapa for the SharpDevelop Team
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

using System;
using System.Collections.Generic;

namespace ICSharpCode.TypeSystem
{
	/// <summary>
	/// Represents a resolved entity.
	/// </summary>
	public interface IEntity : ISymbol, ICompilationProvider, INamedElement, IHasAccessibility
	{
		/// <summary>
		/// Gets the entity type.
		/// </summary>
		[Obsolete("Use the SymbolKind property instead.")]
		EntityType EntityType { get; }

		/// <summary>
		/// Gets the short name of the entity.
		/// </summary>
		new string Name { get; }

		/// <summary>
		/// Gets the complete entity region (including header+body)
		/// </summary>
		DomRegion Region { get; }

		/// <summary>
		/// Gets the entity body region.
		/// </summary>
		DomRegion BodyRegion { get; }

		/// <summary>
		/// Gets the declaring class.
		/// For members, this is the class that contains the member.
		/// For nested classes, this is the outer class. For top-level entities, this property returns null.
		/// </summary>
		ITypeDefinition DeclaringTypeDefinition { get; }

		/// <summary>
		/// Gets/Sets the declaring type (incl. type arguments, if any).
		/// This property will return null for top-level entities.
		/// If this is not a specialized member, the value returned is equal to <see cref="DeclaringTypeDefinition"/>.
		/// </summary>
		IType DeclaringType { get; }

		/// <summary>
		/// The assembly in which this entity is defined.
		/// This property never returns null.
		/// </summary>
		IAssembly ParentAssembly { get; }

		/// <summary>
		/// Gets the attributes on this entity.
		/// </summary>
		IList<IAttribute> Attributes { get; }

		/// <summary>
		/// Gets whether this entity is static.
		/// Returns true if either the 'static' or the 'const' modifier is set.
		/// </summary>
		bool IsStatic { get; }

		/// <summary>
		/// Returns whether this entity is abstract.
		/// </summary>
		/// <remarks>Static classes also count as abstract classes.</remarks>
		bool IsAbstract { get; }

		/// <summary>
		/// Returns whether this entity is sealed.
		/// </summary>
		/// <remarks>Static classes also count as sealed classes.</remarks>
		bool IsSealed { get; }

		/// <summary>
		/// Gets whether this member is declared to be shadowing another member with the same name.
		/// </summary>
		bool IsShadowing { get; }

		/// <summary>
		/// Gets whether this member is generated by a macro/compiler feature.
		/// </summary>
		bool IsSynthetic { get; }
	}

	/// <summary>
	/// Represents an unresolved entity.
	/// </summary>
	public interface IUnresolvedEntity : INamedElement, IHasAccessibility
	{
		/// <summary>
		/// Gets the entity type.
		/// </summary>
		SymbolKind SymbolKind { get; }

		/// <summary>
		/// Gets the complete entity region (including header+body)
		/// </summary>
		DomRegion Region { get; }

		/// <summary>
		/// Gets the entity body region.
		/// </summary>
		DomRegion BodyRegion { get; }

		/// <summary>
		/// Gets the declaring class.
		/// </summary>
		IUnresolvedTypeDefinition DeclaringTypeDefinition { get; }

		/// <summary>
		/// Gets the parsed file in which this entity is defined.
		/// </summary>
		IUnresolvedFile UnresolvedFile { get; }

		/// <summary>
		/// Gets the attributes on this entity.
		/// </summary>
		IList<IUnresolvedAttribute> Attributes { get; }

		/// <summary>
		/// Gets whether this entity is static.
		/// </summary>
		bool IsStatic { get; }

		/// <summary>
		/// Returns whether this entity is abstract.
		/// </summary>
		bool IsAbstract { get; }

		/// <summary>
		/// Returns whether this entity is sealed.
		/// </summary>
		bool IsSealed { get; }

		/// <summary>
		/// Gets whether this member is declared to be shadowing another member with the same name.
		/// </summary>
		bool IsShadowing { get; }

		/// <summary>
		/// Gets whether this member is generated by a macro/compiler feature.
		/// </summary>
		bool IsSynthetic { get; }
	}

	/// <summary>
	/// Method/field/property/event.
	/// </summary>
	public interface IUnresolvedMember : IUnresolvedEntity, IMemberReference
	{
		/// <summary>
		/// Gets the return type of this member.
		/// </summary>
		ITypeReference ReturnType { get; }

		/// <summary>
		/// Gets whether this member is explicitly implementing an interface.
		/// </summary>
		bool IsExplicitInterfaceImplementation { get; }

		/// <summary>
		/// Gets the interfaces that are explicitly implemented by this member.
		/// </summary>
		IList<IMemberReference> ExplicitInterfaceImplementations { get; }

		/// <summary>
		/// Gets if the member is virtual.
		/// </summary>
		bool IsVirtual { get; }

		/// <summary>
		/// Gets whether this member is overriding another member.
		/// </summary>
		bool IsOverride { get; }

		/// <summary>
		/// Gets if the member can be overridden.
		/// </summary>
		bool IsOverridable { get; }

		/// <summary>
		/// Resolves the member.
		/// </summary>
		new IMember Resolve(ITypeResolveContext context);

		/// <summary>
		/// Creates the resolved member.
		/// </summary>
		IMember CreateResolved(ITypeResolveContext context);
	}

	/// <summary>
	/// Represents an unresolved class, enum, interface, struct, delegate or VB module.
	/// </summary>
	public interface IUnresolvedTypeDefinition : ITypeReference, IUnresolvedEntity
	{
		TypeKind Kind { get; }

		FullTypeName FullTypeName { get; }
		IList<ITypeReference> BaseTypes { get; }
		IList<IUnresolvedTypeParameter> TypeParameters { get; }

		IList<IUnresolvedTypeDefinition> NestedTypes { get; }
		IList<IUnresolvedMember> Members { get; }

		IEnumerable<IUnresolvedMethod> Methods { get; }
		IEnumerable<IUnresolvedProperty> Properties { get; }
		IEnumerable<IUnresolvedField> Fields { get; }
		IEnumerable<IUnresolvedEvent> Events { get; }

		/// <summary>
		/// Gets whether the type definition contains extension methods.
		/// </summary>
		bool? HasExtensionMethods { get; }

		/// <summary>
		/// Gets whether the partial modifier is set on this part of the type definition.
		/// </summary>
		bool IsPartial { get; }

		/// <summary>
		/// Gets whether this unresolved type definition causes the addition of a default constructor
		/// if no other constructor is present.
		/// </summary>
		bool AddDefaultConstructorIfRequired { get; }

		/// <summary>
		/// Looks up the resolved type definition from the context corresponding to this unresolved type definition.
		/// </summary>
		new IType Resolve(ITypeResolveContext context);

		/// <summary>
		/// Creates the resolve context for this type definition.
		/// </summary>
		ITypeResolveContext CreateResolveContext(ITypeResolveContext parentContext);
	}

	/// <summary>
	/// Represents an unresolved method.
	/// </summary>
	public interface IUnresolvedMethod : IUnresolvedParameterizedMember
	{
		/// <summary>
		/// Gets the attributes associated with the return type.
		/// </summary>
		IList<IUnresolvedAttribute> ReturnTypeAttributes { get; }

		IList<IUnresolvedTypeParameter> TypeParameters { get; }

		bool IsConstructor { get; }
		bool IsDestructor { get; }
		bool IsOperator { get; }

		/// <summary>
		/// Gets whether the method is a C#-style partial method.
		/// </summary>
		bool IsPartial { get; }

		/// <summary>
		/// Gets whether the method is a C#-style async method.
		/// </summary>
		bool IsAsync { get; }

		bool IsExtensionMethod { get; }

		[Obsolete("Use IsPartial && !HasBody instead")]
		bool IsPartialMethodDeclaration { get; }

		[Obsolete("Use IsPartial && HasBody instead")]
		bool IsPartialMethodImplementation { get; }

		/// <summary>
		/// Gets whether the method has a body.
		/// </summary>
		bool HasBody { get; }

		/// <summary>
		/// If this method is an accessor, returns a reference to the corresponding property/event.
		/// </summary>
		IUnresolvedMember AccessorOwner { get; }

		/// <summary>
		/// Resolves the member.
		/// </summary>
		new IMethod Resolve(ITypeResolveContext context);
	}

	/// <summary>
	/// Represents an unresolved property or indexer.
	/// </summary>
	public interface IUnresolvedProperty : IUnresolvedParameterizedMember
	{
		bool CanGet { get; }
		bool CanSet { get; }

		IUnresolvedMethod Getter { get; }
		IUnresolvedMethod Setter { get; }

		bool IsIndexer { get; }

		/// <summary>
		/// Resolves the member.
		/// </summary>
		new IProperty Resolve(ITypeResolveContext context);
	}

	/// <summary>
	/// Represents an unresolved field or constant.
	/// </summary>
	public interface IUnresolvedField : IUnresolvedMember
	{
		/// <summary>
		/// Gets whether this field is readonly.
		/// </summary>
		bool IsReadOnly { get; }

		/// <summary>
		/// Gets whether this field is volatile.
		/// </summary>
		bool IsVolatile { get; }

		/// <summary>
		/// Gets whether this field is a constant.
		/// </summary>
		bool IsConst { get; }

		/// <summary>
		/// Gets whether this field is a fixed size buffer.
		/// </summary>
		bool IsFixed { get; }

		IConstantValue ConstantValue { get; }

		/// <summary>
		/// Resolves the member.
		/// </summary>
		new IField Resolve(ITypeResolveContext context);
	}

	/// <summary>
	/// Represents an unresolved event.
	/// </summary>
	public interface IUnresolvedEvent : IUnresolvedMember
	{
		bool CanAdd { get; }
		bool CanRemove { get; }
		bool CanInvoke { get; }

		IUnresolvedMethod AddAccessor { get; }
		IUnresolvedMethod RemoveAccessor { get; }
		IUnresolvedMethod InvokeAccessor { get; }

		/// <summary>
		/// Resolves the member.
		/// </summary>
		new IEvent Resolve(ITypeResolveContext context);
	}
}
