<Project Sdk="LibreWPF.Sdk">
  <PropertyGroup>
    <OpenDevelopAddin>true</OpenDevelopAddin>
    <OpenDevelopAddinKind>InProcessDependency</OpenDevelopAddinKind>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ICSharpCode.Data.Core.UI</RootNamespace>
    <AssemblyName>ICSharpCode.Data.Core.UI</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <OutputPath>..\..\..\..\..\AddIns\DisplayBindings\Data\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\..\Main\ICSharpCode.SharpDevelop.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" Private="false" />
    <ProjectReference Include="..\..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" Private="false" />
    <ProjectReference Include="..\..\..\..\Main\ICSharpCode.Core.Presentation\ICSharpCode.Core.Presentation.csproj" Private="false" />
    <ProjectReference Include="..\ICSharpCode.Data.Core\ICSharpCode.Data.Core.csproj" />
  </ItemGroup>
</Project>
