using System; using System.IO; using System.Threading; using System.Threading.Tasks; using ICSharpCode.SharpDevelop.Designer.Remote;
namespace ICSharpCode.MewUIDesigner;
sealed class MewUIDesignerHostClient : DesignerHostProcessClient, IDesignHostClient
{
	readonly string hostDll; public string DocumentId { get; } = Guid.NewGuid().ToString("N"); MewUIDesignerHostClient(string path) => hostDll = path;
	public static async Task<MewUIDesignerHostClient> CreateAsync(CancellationToken token = default) { var path = Path.Combine(Path.GetDirectoryName(typeof(MewUIDesignerHostClient).Assembly.Location)!, "Host", "MewUIDesigner.Host.dll"); var client = new MewUIDesignerHostClient(path); await client.StartAsync(token).ConfigureAwait(false); return client; }
	protected override string GetChildDllPath() => hostDll; void Stamp(DesignerDocumentSnapshot s) { s.SessionId = SessionId; s.DocumentId = DocumentId; }
	public Task<DesignerSessionState> OpenAsync(DesignerDocumentSnapshot s, CancellationToken t = default) { Stamp(s); return InvokeAsync<DesignerSessionState>("session/open", new { snapshot = s }, t); } public Task<DesignerSessionState> UpdateAsync(DesignerDocumentSnapshot s, CancellationToken t = default) { Stamp(s); return InvokeAsync<DesignerSessionState>("session/update", new { snapshot = s }, t); }
	public Task<DesignerEditSet> FlushAsync(long v, CancellationToken t = default) => InvokeAsync<DesignerEditSet>("session/flush", new { baseVersion = v }, t); public Task<DesignerSessionState> SetPropertyAsync(long v, string id, string p, string value, CancellationToken t = default) => InvokeAsync<DesignerSessionState>("design/set-property", new { baseVersion = v, elementId = id, propertyName = p, value }, t); public Task<DesignerSessionState> AddElementAsync(long v, string parent, DesignerToolboxItemInfo item, string name, double x, double y, CancellationToken t = default) => InvokeAsync<DesignerSessionState>("design/add-element", new { baseVersion = v, parentId = parent, item, proposedName = name, x, y }, t); public Task<DesignerSessionState> DeleteElementsAsync(long v, string[] ids, CancellationToken t = default) => InvokeAsync<DesignerSessionState>("design/delete-elements", new { baseVersion = v, elementIds = ids }, t); public Task<DesignerSessionState> RenameAsync(long v, string id, string name, CancellationToken t = default) => InvokeAsync<DesignerSessionState>("design/rename", new { baseVersion = v, elementId = id, newName = name }, t); public Task<DesignerSessionState> UndoAsync(long v) => InvokeAsync<DesignerSessionState>("design/undo", new { baseVersion = v }, default); public Task<DesignerSessionState> RedoAsync(long v) => InvokeAsync<DesignerSessionState>("design/redo", new { baseVersion = v }, default);
	public Task PingAsync(CancellationToken t = default) => InvokeAsync<object>("ping", null!, t); public Task ShutdownAsync(CancellationToken t = default) => InvokeAsync<object>("shutdown", null!, t, TimeSpan.FromSeconds(3)); public Task<DesignerSessionState> SetEventAsync(long v, string id, string e, string h, CancellationToken t = default) => throw new NotSupportedException(); public Task<DesignerSessionState> SetBoundsAsync(long v, string id, double x, double y, double w, double h, CancellationToken t = default) => throw new NotSupportedException(); public Task<DesignerHitTestResult> HitTestAsync(long v, double x, double y, CancellationToken t = default) => throw new NotSupportedException();
}
