// <auto-generated>
//   Generated by the OpenDevelop GTK designer from MainWindow.ui. Do not edit: it is
//   rewritten whenever the .ui file's signals change. Handler bodies belong in the
//   other part of MainWindow.
// </auto-generated>
#nullable enable

namespace GtkDesignerFixture
{
	partial class MainWindow
	{
		/// <summary>Builds MainWindow.ui and connects its &lt;signal&gt; handlers to this object.
		/// GtkBuilder cannot resolve handler names to C# methods (it aborts on them), so the
		/// signals are removed before building and connected through Gir.Core events here.</summary>
		public global::Gtk.Builder BuildUi(string uiPath)
		{
			var document = global::System.Xml.Linq.XDocument.Load(uiPath);
			foreach (var signal in global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Where(document.Descendants(), e => e.Name.LocalName == "signal")))
				signal.Remove();
			var builder = global::Gtk.Builder.New();
			builder.AddFromString(document.ToString(), -1);
			return builder;
		}
	}
}
