<Project Sdk="LibreWPF.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.WinUIXamlDesigner.UnoDesignHost</AssemblyName>
    <RootNamespace>ICSharpCode.WinUIXamlDesigner.UnoDesignHost</RootNamespace>
    <OutputPath>..\..\..\..\..\AddIns\DisplayBindings\WinUIXamlDesigner\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinUIXamlDesigner.AddIn\ICSharpCode.WinUIXamlDesigner.csproj" Private="false" />
    <ProjectReference Include="..\..\..\..\Main\Designer\Designer.Remote\Designer.Remote.csproj" />
    <ProjectReference Include="..\..\..\..\Main\Designer\Designer.Presentation\Designer.Presentation.csproj" />
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
  </ItemGroup>
</Project>
