<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WinUIXamlDesigner.UnoDesignHost.Remote</AssemblyName>
    <RootNamespace>ICSharpCode.WinUIXamlDesigner.UnoDesignHost</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\WinUIXamlDesigner.UnoDesignHost\UnoDesignClient.cs" Link="UnoDesignClient.cs" />
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
    <ProjectReference Include="..\..\..\..\Main\Designer\Designer.Remote\Designer.Remote.csproj" />
    <ProjectReference Include="..\WinUIXamlDesigner.UnoHost\WinUIXamlDesigner.UnoHost.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
