<Project Sdk="LibreWPF.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.GtkDesigner</AssemblyName>
    <RootNamespace>ICSharpCode.GtkDesigner</RootNamespace>
    <OpenDevelopAddin>true</OpenDevelopAddin>
    <OpenDevelopAddinKind>InProcess</OpenDevelopAddinKind>
    <OutputPath>..\..\..\..\AddIns\DisplayBindings\GtkDesigner\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\GtkUi.xshd" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="GtkUiDocumentEditor.cs" />
    <ProjectReference Include="..\..\..\Main\Base\Project\ICSharpCode.SharpDevelop.csproj" Private="false" />
    <ProjectReference Include="..\..\..\Main\Core\Project\ICSharpCode.Core.csproj" Private="false" />
    <ProjectReference Include="..\..\..\Main\ICSharpCode.SharpDevelop.Widgets\Project\ICSharpCode.SharpDevelop.Widgets.csproj" Private="false" />
    <ProjectReference Include="..\..\..\Main\Designer\Designer.Remote\Designer.Remote.csproj" Private="false" />
	  <ProjectReference Include="..\..\..\Main\Designer\Designer.Shell\Designer.Shell.csproj" Private="false" />
    <ProjectReference Include="..\GtkDesigner.Host\GtkDesigner.Host.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" SkipGetTargetFrameworkProperties="true" />
    <PackageReference Include="LeXtudio.DevFlow.Agent.Core" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>
</Project>
